/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accept: typeof import('./src/components/ui/atoms/icon/_internal/accept.vue')['default']
    AddCirc: typeof import('./src/components/ui/atoms/icon/_internal/add-circ.vue')['default']
    AddRect: typeof import('./src/components/ui/atoms/icon/_internal/add-rect.vue')['default']
    ArrowR: typeof import('./src/components/ui/atoms/icon/_internal/arrow-r.vue')['default']
    Audio: typeof import('./src/components/ui/atoms/icon/_internal/audio.vue')['default']
    ChatPlus: typeof import('./src/components/ui/atoms/icon/_internal/chat-plus.vue')['default']
    Clear: typeof import('./src/components/ui/atoms/icon/_internal/clear.vue')['default']
    Clipboard: typeof import('./src/components/ui/atoms/icon/_internal/clipboard.vue')['default']
    ClipboardDash: typeof import('./src/components/ui/atoms/icon/_internal/clipboard-dash.vue')['default']
    CloudOutqoing: typeof import('./src/components/ui/atoms/icon/_internal/cloud-outqoing.vue')['default']
    Del: typeof import('./src/components/ui/atoms/icon/_internal/del.vue')['default']
    DelOpaque: typeof import('./src/components/ui/atoms/icon/_internal/del-opaque.vue')['default']
    Edit: typeof import('./src/components/ui/atoms/icon/_internal/edit.vue')['default']
    Erase: typeof import('./src/components/ui/atoms/icon/_internal/erase.vue')['default']
    Export: typeof import('./src/components/ui/atoms/icon/_internal/export.vue')['default']
    ExportCloud: typeof import('./src/components/ui/atoms/icon/_internal/export-cloud.vue')['default']
    Globe: typeof import('./src/components/ui/atoms/icon/_internal/globe.vue')['default']
    Info: typeof import('./src/components/ui/atoms/icon/_internal/info.vue')['default']
    InfoOpaque: typeof import('./src/components/ui/atoms/icon/_internal/info-opaque.vue')['default']
    ListBars: typeof import('./src/components/ui/atoms/icon/_internal/list-bars.vue')['default']
    Logseq: typeof import('./src/components/ui/atoms/icon/_internal/logseq.vue')['default']
    Md: typeof import('./src/components/ui/atoms/icon/_internal/md.vue')['default']
    Menu: typeof import('./src/components/ui/atoms/icon/_internal/menu.vue')['default']
    Mic: typeof import('./src/components/ui/atoms/icon/_internal/mic.vue')['default']
    Pause: typeof import('./src/components/ui/atoms/icon/_internal/pause.vue')['default']
    Play: typeof import('./src/components/ui/atoms/icon/_internal/play.vue')['default']
    Plus: typeof import('./src/components/ui/atoms/icon/_internal/plus.vue')['default']
    PrtBtn: typeof import('./src/components/ui/atoms/btn/PrtBtn.vue')['default']
    PrtIcon: typeof import('./src/components/ui/atoms/icon/PrtIcon.vue')['default']
    Refresh: typeof import('./src/components/ui/atoms/icon/_internal/refresh.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Save: typeof import('./src/components/ui/atoms/icon/_internal/save.vue')['default']
    Send: typeof import('./src/components/ui/atoms/icon/_internal/send.vue')['default']
    Speaker: typeof import('./src/components/ui/atoms/icon/_internal/speaker.vue')['default']
    Spinner: typeof import('./src/components/ui/atoms/icon/_internal/spinner.vue')['default']
    Stop: typeof import('./src/components/ui/atoms/icon/_internal/stop.vue')['default']
    Text: typeof import('./src/components/ui/atoms/icon/_internal/text.vue')['default']
    User: typeof import('./src/components/ui/atoms/icon/_internal/user.vue')['default']
    Users: typeof import('./src/components/ui/atoms/icon/_internal/users.vue')['default']
    X: typeof import('./src/components/ui/atoms/icon/_internal/x.vue')['default']
    XCirc: typeof import('./src/components/ui/atoms/icon/_internal/x-circ.vue')['default']
  }
}
